import { SecurityIncident, VisitorLog, SecurityAlert } from "./types";

// Sample data for security incidents
export const securityIncidentsData: SecurityIncident[] = [
  {
    id: "INC001",
    title: "Vi phạm giờ giới nghiêm",
    description: "Sinh viên vào ký túc xá sau 23:00",
    type: "curfew",
    status: "resolved",
    severity: "low",
    reportDate: "2023-11-10T21:30:00",
    location: "Cổng chính",
    reportedBy: "Bảo vệ Nguyễn Văn X",
    involvedStudents: [{ id: "SV001", name: "Nguyễn Văn A" }],
  },
  {
    id: "INC002",
    title: "Mất tài sản cá nhân",
    description: "Laptop bị mất trong phòng khi sinh viên đi học",
    type: "theft",
    status: "investigating",
    severity: "high",
    reportDate: "2023-11-08T14:20:00",
    location: "Phòng P101",
    reportedBy: "Trần Bình B",
    involvedStudents: [{ id: "SV002", name: "Trần Bình B" }],
  },
  {
    id: "INC003",
    title: "Gây ồn ào sau giờ nghỉ",
    description: "Tổ chức sinh nhật gây ồn ào sau 22:00",
    type: "noise",
    status: "resolved",
    severity: "medium",
    reportDate: "2023-11-07T22:45:00",
    location: "Phòng P201",
    reportedBy: "Sinh viên tầng 2",
    involvedStudents: [
      { id: "SV006", name: "Vũ Minh F" },
      { id: "SV007", name: "Đặng Thu G" },
    ],
  },
  {
    id: "INC004",
    title: "Sử dụng thiết bị điện không an toàn",
    description: "Sử dụng bếp điện trong phòng gây cháy nhỏ",
    type: "fire_hazard",
    status: "resolved",
    severity: "high",
    reportDate: "2023-11-05T18:30:00",
    location: "Phòng P302",
    reportedBy: "Nhân viên quản lý",
    involvedStudents: [{ id: "SV008", name: "Lý Văn H" }],
  },
  {
    id: "INC005",
    title: "Người lạ vào ký túc xá",
    description:
      "Phát hiện người không phải sinh viên vào ký túc xá không qua kiểm soát",
    type: "trespassing",
    status: "pending",
    severity: "high",
    reportDate: "2023-11-09T16:15:00",
    location: "Tầng 1, Khu A",
    reportedBy: "Bảo vệ Trần Văn Y",
    involvedStudents: [],
  },
  {
    id: "INC006",
    title: "Hút thuốc trong khuôn viên",
    description: "Sinh viên hút thuốc trong khu vực cấm",
    type: "rule_violation",
    status: "resolved",
    severity: "medium",
    reportDate: "2023-11-06T10:45:00",
    location: "Sân sau, Khu B",
    reportedBy: "Nhân viên vệ sinh",
    involvedStudents: [{ id: "SV010", name: "Hoàng Văn K" }],
  },
];

// Sample data for visitor logs
export const visitorLogsData: VisitorLog[] = [
  {
    id: "VIS001",
    visitorName: "Nguyễn Thị X",
    visitorId: "123456789",
    purpose: "Thăm người thân",
    visitingStudent: { id: "SV001", name: "Nguyễn Văn A", room: "P101" },
    checkInTime: "2023-11-10T14:30:00",
    checkOutTime: "2023-11-10T16:45:00",
    status: "completed",
  },
  {
    id: "VIS002",
    visitorName: "Trần Văn Y",
    visitorId: "987654321",
    purpose: "Bảo trì điều hòa",
    visitingStudent: null,
    checkInTime: "2023-11-10T09:15:00",
    checkOutTime: "2023-11-10T11:30:00",
    status: "completed",
  },
  {
    id: "VIS003",
    visitorName: "Lê Thị Z",
    visitorId: "456123789",
    purpose: "Thăm người thân",
    visitingStudent: { id: "SV003", name: "Lê Thị C", room: "P102" },
    checkInTime: "2023-11-09T18:00:00",
    checkOutTime: "2023-11-09T19:30:00",
    status: "completed",
  },
  {
    id: "VIS004",
    visitorName: "Phạm Văn W",
    visitorId: "789123456",
    purpose: "Giao hàng",
    visitingStudent: { id: "SV002", name: "Trần Bình B", room: "P101" },
    checkInTime: "2023-11-11T12:00:00",
    checkOutTime: null,
    status: "active",
  },
  {
    id: "VIS005",
    visitorName: "Đoàn Văn V",
    visitorId: "321654987",
    purpose: "Sửa chữa internet",
    visitingStudent: null,
    checkInTime: "2023-11-11T08:30:00",
    checkOutTime: null,
    status: "active",
  },
];

// Sample data for security alerts
export const securityAlertsData: SecurityAlert[] = [
  {
    id: 1,
    title: "Bão cấp 9 đang tiến về khu vực",
    description:
      "Chuẩn bị các biện pháp phòng chống bão. Sinh viên không ra khỏi ký túc xá.",
    severity: "high",
    dateCreated: "2023-11-11T08:00:00",
    expiryDate: "2023-11-13T20:00:00",
    isActive: true,
  },
  {
    id: 2,
    title: "Bảo trì hệ thống điện",
    description:
      "Hệ thống điện sẽ bị cắt từ 14:00-16:00 ngày 12/11/2023. Sinh viên lưu ý sạc thiết bị trước thời gian này.",
    severity: "medium",
    dateCreated: "2023-11-10T10:00:00",
    expiryDate: "2023-11-12T16:00:00",
    isActive: true,
  },
  {
    id: 3,
    title: "Kiểm tra an toàn PCCC",
    description:
      "Kiểm tra hệ thống phòng cháy chữa cháy vào ngày 15/11/2023. Mọi người chú ý phối hợp.",
    severity: "low",
    dateCreated: "2023-11-09T09:00:00",
    expiryDate: "2023-11-15T18:00:00",
    isActive: true,
  },
  {
    id: 4,
    title: "Tăng cường an ninh dịp lễ",
    description: "Tăng cường kiểm soát ra vào ký túc xá trong dịp lễ 20/11.",
    severity: "medium",
    dateCreated: "2023-11-08T10:30:00",
    expiryDate: "2023-11-21T23:59:00",
    isActive: true,
  },
];
