export const services = [
  {
    id: 1,
    name: "Giặt ủi",
    description:
      "Dịch vụ giặt ủi quần áo cho sinh viên ký túc xá\n- Giặt thường: 15,000đ/kg\n- Giặt hấp: 25,000đ/kg\n- Giặt đồ đặc biệt: 35,000đ/kg",
    price: 15000,
    unit: "kg",
    provider: "Công ty TNHH Giặt ủi Sạch & Sạch",
    available: true,
    subscriptions: 1250,
  },
  {
    id: 2,
    name: "Điện nước",
    description:
      "Dịch vụ cung cấp và bảo trì điện nước trong ký túc xá\n- Điện: 3,500đ/kwh\n- Nước: 15,000đ/m3",
    price: 3500,
    unit: "kwh",
    provider: "Công ty Điện lực TP.HCM",
    available: true,
    subscriptions: 5000,
  },
  {
    id: 3,
    name: "Internet",
    description:
      "Dịch vụ internet tốc độ cao dành cho sinh viên\n- Tốc độ: 100Mbps\n- Không giới hạn dung lượng\n- Hỗ trợ kỹ thuật 24/7",
    price: 200000,
    unit: "tháng",
    provider: "FPT Telecom",
    available: true,
    subscriptions: 3000,
  },
  {
    id: 4,
    name: "Vệ sinh phòng",
    description:
      "Dịch vụ vệ sinh phòng ở định kỳ hoặc theo yêu cầu\n- Quét dọn, lau nhà\n- Vệ sinh nhà vệ sinh\n- Đổ rác\n- Thay ga giường",
    price: 100000,
    unit: "lần",
    provider: "Công ty Vệ sinh Xanh",
    available: true,
    subscriptions: 800,
  },
  {
    id: 5,
    name: "Gửi xe",
    description:
      "Dịch vụ trông giữ xe máy, xe đạp cho sinh viên\n- Bảo vệ 24/7\n- Có camera giám sát\n- Bảo hiểm mất cắp",
    price: 100000,
    unit: "tháng",
    provider: "Ban Quản lý KTX",
    available: true,
    subscriptions: 2000,
  },
  {
    id: 6,
    name: "Căn tin",
    description:
      "Dịch vụ ăn uống tại căn tin ký túc xá\n- Phục vụ 3 bữa/ngày\n- Đa dạng món ăn\n- Đảm bảo vệ sinh an toàn thực phẩm",
    price: 30000,
    unit: "suất",
    provider: "Công ty TNHH Thực phẩm Ngon",
    available: false,
    subscriptions: 1500,
  },
];

export const serviceRequests = [
  {
    id: "REQ001",
    studentName: "Nguyễn Văn A",
    studentId: "20110001",
    roomName: "P.101",
    serviceType: "Giặt ủi",
    description: "Giặt 3kg quần áo thường",
    status: "completed",
    requestDate: "2024-03-10T08:00:00Z",
    completedDate: "2024-03-10T15:00:00Z",
    urgency: "low",
  },
  {
    id: "REQ002",
    studentName: "Trần Thị B",
    studentId: "20110015",
    roomName: "P.205",
    serviceType: "Vệ sinh phòng",
    description: "Dọn dẹp phòng và vệ sinh nhà vệ sinh",
    status: "in_progress",
    requestDate: "2024-03-11T09:30:00Z",
    completedDate: null,
    urgency: "medium",
  },
  {
    id: "REQ003",
    studentName: "Lê Văn C",
    studentId: "20110023",
    roomName: "P.302",
    serviceType: "Internet",
    description: "Mạng yếu, không thể học online",
    status: "pending",
    requestDate: "2024-03-11T14:00:00Z",
    completedDate: null,
    urgency: "high",
  },
  {
    id: "REQ004",
    studentName: "Phạm Thị D",
    studentId: "20110045",
    roomName: "P.401",
    serviceType: "Điện nước",
    description: "Bóng đèn phòng ngủ bị cháy",
    status: "cancelled",
    requestDate: "2024-03-09T16:20:00Z",
    completedDate: "2024-03-09T16:45:00Z",
    urgency: "medium",
  },
  {
    id: "REQ005",
    studentName: "Hoàng Văn E",
    studentId: "20110056",
    roomName: "P.103",
    serviceType: "Giặt ủi",
    description: "Giặt hấp 2kg quần áo",
    status: "pending",
    requestDate: "2024-03-11T15:30:00Z",
    completedDate: null,
    urgency: "low",
  },
];
