// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAmenity(arg1) {
  return window['go']['app']['App']['CreateAmenity'](arg1);
}

export function CreateContract(arg1) {
  return window['go']['app']['App']['CreateContract'](arg1);
}

export function CreateMaintenanceHistory(arg1) {
  return window['go']['app']['App']['CreateMaintenanceHistory'](arg1);
}

export function CreateRoom(arg1) {
  return window['go']['app']['App']['CreateRoom'](arg1);
}

export function CreateRoomCategory(arg1) {
  return window['go']['app']['App']['CreateRoomCategory'](arg1);
}

export function DeleteAmenity(arg1) {
  return window['go']['app']['App']['DeleteAmenity'](arg1);
}

export function DeleteMaintenanceHistory(arg1) {
  return window['go']['app']['App']['DeleteMaintenanceHistory'](arg1);
}

export function DeleteRoom(arg1) {
  return window['go']['app']['App']['DeleteRoom'](arg1);
}

export function GetAmenityDetails(arg1) {
  return window['go']['app']['App']['GetAmenityDetails'](arg1);
}

export function GetContractDetails(arg1) {
  return window['go']['app']['App']['GetContractDetails'](arg1);
}

export function GetListAmenities(arg1) {
  return window['go']['app']['App']['GetListAmenities'](arg1);
}

export function GetListContracts(arg1, arg2) {
  return window['go']['app']['App']['GetListContracts'](arg1, arg2);
}

export function GetListMaintenanceHistories(arg1, arg2) {
  return window['go']['app']['App']['GetListMaintenanceHistories'](arg1, arg2);
}

export function GetListRoomCategories(arg1) {
  return window['go']['app']['App']['GetListRoomCategories'](arg1);
}

export function GetListRooms(arg1) {
  return window['go']['app']['App']['GetListRooms'](arg1);
}

export function GetListUsers(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetListUsers'](arg1, arg2, arg3, arg4, arg5);
}

export function GetMaintenanceHistoryDetails(arg1) {
  return window['go']['app']['App']['GetMaintenanceHistoryDetails'](arg1);
}

export function GetRoomCategoryDetails(arg1) {
  return window['go']['app']['App']['GetRoomCategoryDetails'](arg1);
}

export function GetRoomDetails(arg1) {
  return window['go']['app']['App']['GetRoomDetails'](arg1);
}

export function GetUserDetails(arg1) {
  return window['go']['app']['App']['GetUserDetails'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function UpdateAmenity(arg1, arg2) {
  return window['go']['app']['App']['UpdateAmenity'](arg1, arg2);
}

export function UpdateMaintenanceHistory(arg1, arg2) {
  return window['go']['app']['App']['UpdateMaintenanceHistory'](arg1, arg2);
}

export function UpdateRoom(arg1, arg2) {
  return window['go']['app']['App']['UpdateRoom'](arg1, arg2);
}
